### PR TITLE
Fix promise compatibility

### LINKED ISSUE #62: Add promise support
``` js
import Xray from 'x-ray';

let scraper = Xray();

scraper(url, {
    items: scraper('.scope', [
        {
            link: '.link@href'
        }
    ])
})
.then(
     result => {
        // All done
     },
     error => {
        // There're errors
     }
});
```

### PR DESCRIPTION
**Pull request by leonardodino**
### Description

Fix Promise compatibility (allows use with `async/await`).

Currently, it's ignoring the second parameter, meaning it won't ever run `catch` blocks.

closes #62 

### Checklist

- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by lathropd** [comment]
this needs a test case

**Comment by leonardodino** [comment]
Rebased and added a test. (:

(I'm using it in production via `async/await`)

File: test/xray_spec.js [hunk 1]
```diff
@@ -468,25 +469,40 @@ describe('Xray basics', function () {
...
+        assert(errorHandler.called === false, 'error handler never called')
+      })
+    })
+
+    it('should Promisify and pass rejections to promise', function () {
+      var resHandler = sinon.fake()
+      var errorHandler = sinon.fake()
+
+      var xray = x('https://127.0.0.1:666/', '.tags', [['li']])
+      process.once('unhandledRejection', noop)
```
Comment (leonardodino) [inline test/xray_spec.js]: I couldn't find a better (latency and reproducibility wise) way than requesting to a non-existing localhost service.

Unfortunately something in the dependency chain (`x-ray-crawler`/`superagent`) warns about a `Unhandled Rejection`.

Although it is ultimately handled, as it calls the second argument with the exact same error as it's supposedly unhandled.

Probably something to do with asynchronous handling of exceptions, or handling it after a loop in the code. 🤷‍♂
